site_name: TwoMoons Project
site_url: https://twomoonsproject.com/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.selections
    - toc.intergrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal 
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.pathconverter:
      base_path: 'TwoMoons-Project'  # Replace with your repository name
      relative_path: ''  # Leave empty
      absolute: true
  - pymdownx.highlight:
      anchor_linenums: False # make "true" causes conflict error with line 1, column 1 ("expected <block end>, but found '<block sequence start>'")
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.smartsymbols # new additions start in this line
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
  - tables

plugins:
  - search:
      enabled: True

copyright:
  "Copyright 2024 EnKryptic Labs"

